return {
	"nvim-treesitter/nvim-treesitter",
	event = "VeryLazy",
	branch = "master",
	main = "nvim-treesitter.configs",
	opts = {
		ensure_installed = {
			"lua",
			"toml",
			"rust",
			"toml",
			"nix",
			"javascript",
			"typescript",
			"tsx",
			"css",
			"html",
			"markdown",
			"markdown_inline",
			"c",
			"cpp",
			"cmake",
			"go",
			"c_sharp",
		},
		highlight = { enable = true },
	},
}
